### ISSUE TITLE
Negative Dark Power

### ISSUE THREAD

**Issue by Gonduin** [DrasticDemiseFTBPacks/Banished#111]
I have seen multiple reports of people getting negative dark power but I haven't seen anyone list the cause. 

The following quests can result in negative dark power:
Sugar Cane (only requires a reputation of 1, but consumes 5 when completed)
Sapling (only requires a reputation of 10, but consumes 12 when completed)
String (only requires a reputation of 1, but consumes 2 when completed)
Soulbound (only requires a reputation of 10, but consumes 25 when completed)

I haven't checked the other quest lines, but anytime you have a reputation limit for the task requirement set lower than you have for the reward it can result in negative dark power.

**Comment by DrasticDemise** [comment]
Thank you, I will take a look at those.

**Comment by ArcticHowler** [comment]
Don't remember which one is was, but there was one that cost me less than it required as well... Either that or I somehow gained dark power from non-quest sources...
