### ISSUE TITLE
Question/Issue: Random Explosions

### ISSUE THREAD

**Issue by 0Bheka0** [DrasticDemiseFTBPacks/Banished#12]
There are seemingly random explosions all over the world slowing eating away at the terrain which are probably mob related. What causes these and are they intended?
Edit: It seems these may  be caused by special skeletons just randomly shooting exploding arrows at other mobs.

**Comment by DrasticDemise** [comment]
Those are from the mod Epic Siege Mod, and it is most likely the mobs tunneling to you. This is intended, though them dropping items on the ground is not and does seem to cause lag.
