### ISSUE TITLE
Issues: Utility Mobs

### ISSUE THREAD

**Issue by 0Bheka0** [DrasticDemiseFTBPacks/Banished#16]
If they don't receive their own questline in the future there should be at least an allusion to the manual recipes in the quest as they are non-NEI-searchable. Futhermore collossi just refuse to form no matter what.

**Comment by DrasticDemise** [comment]
There is one for the turrets but I will add on some more for the other ones, though there isn't much purpose in a following crafting table or anvil IMO. The only useful ones are the golems and turrets in most cases.

**Comment by DrasticDemise** [comment]
The manuals are now quest rewards.
