### ISSUE TITLE
Mod Suggestions

### ISSUE THREAD

**Issue by DrasticDemise** [DrasticDemiseFTBPacks/Banished#18]
Post any mod suggestions below.

**Comment by Blorog1** [comment]
I feel like Forbidden Magic and Witching Gadgets should be added, they are both Thaumcraft addons.

**Comment by Milobe115** [comment]
+1 for Forbidden Magic. Adds a little bit of cross-compatibility w/ Blood Magic and Botania, and it blends w/ the theme, IMO.

**Comment by DrasticDemise** [comment]
Hmm. Thought I added those. Will be in next update

**Comment by joakibj** [comment]
Have you updated to the most recent version of Automagy (0.26)?

Tuhljin has made Magic Mirrors 100x more useful and awesome with the Melding Mirror.

**Comment by DrasticDemise** [comment]
Will be added next update.
