### ISSUE TITLE
TPS problems on v0.0.5

### ISSUE THREAD

**Issue by MojiRS** [DrasticDemiseFTBPacks/Banished#21]
I'm still experiencing TPS problems due to mobs on v0.0.5. After playing normally for an hour or so, my TPS was down to around 10. After killing all mobs using /cofh killall, my TPS increased to about 15 - still not great, and there weren't even many mobs:

![2015-06-11_13 57 28](https://cloud.githubusercontent.com/assets/12838251/8118074/e00a623e-1041-11e5-8862-230ae83f66be.png)

Changing to peaceful solved it entirely, causing my TPS to go back up to 20. After switching back to normal, my TPS started steadily decreasing again, steadily decreasing from 20 after about 15 seconds.

**Comment by DrasticDemise** [comment]
It may be the xray mobs still. Will check that out.

**Comment by DrasticDemise** [comment]
Should be solved next update, Slashing more ESM configs.
