### ISSUE TITLE
Issue: 0.0.5

### ISSUE THREAD

**Issue by 0Bheka0** [DrasticDemiseFTBPacks/Banished#22]
Dark Power can be driven into an infinite deficit during the fury and mistery spell quests.

**Comment by DrasticDemise** [comment]
Did I not set a reputation detect?

**Comment by DrasticDemise** [comment]
Huh, it says that they have a reputation detect.

**Comment by DrasticDemise** [comment]
This should be fixed. Will have to see though. Thanks!
