### ISSUE TITLE
Cascading Processor

### ISSUE THREAD

**Issue by MojiRS** [DrasticDemiseFTBPacks/Banished#23]
The Cascading Processor from Aura Cascade doesn't appear to function, and isn't even included in the Encyclopedia Aura. Is the Processor not implemented in Aura Cascade yet, or is it disabled for some reason?

Edit: It appears the Processor can still make Arcane Ingots, but it can't process ores.

**Comment by 0Bheka0** [comment]
For it to process ores a mod that introduces forge oredictonary dusts would be needed if i recall correctly.
Edit: This could easily be resolved by adding the pure compatibility mod "Another One Bites The Dust 2"

**Comment by DrasticDemise** [comment]
Will check that out. Thanks
