### ISSUE TITLE
Caveworld Mining Points

### ISSUE THREAD

**Issue by MojiRS** [DrasticDemiseFTBPacks/Banished#24]
While earning mining points works as it should, mining an ore with an Ars Magica spell does not add to your mining points. While I'm not sure if it's possible to specify spells as able to earn mining points, it would be great if you could. I (and I'm sure most other people) stopped using a pick to mine in favor of spells, meaning I'm not earning points for the ores I mine.

**Comment by DrasticDemise** [comment]
The points don't actually have a purpose if you are already inside of the dimension. I think their only purpose at that point is to allow you to tame cavemen. And there doesn't seem a way for me to do that since AM2 doesn't actually "mine" the blocks, it just causes them to drop. Sorry!

**Comment by MojiRS** [comment]
You need 1000 points to access the Deep Caveworld (which is why I wanted the points, as the Deep Caveworld has double ore generation), but, since you can't do anything, don't worry about it!
