### ISSUE TITLE
Issue starting server/ setting up server files

### ISSUE THREAD

**Issue by xerosus** [DrasticDemiseFTBPacks/Banished#27]
I followed the following steps to set up the server https://www.hosthorde.com/forums/resources/installing-minecraft-forge-server.35/
and receive the following crash: (Note that the log starts at the bottom)

12.06 02:21:38 [Multicraft] Looks like a crash, check the server console. Return value: 1
12.06 02:21:38 [Multicraft] Server shut down
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    ... 16 more
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.ClassLoader.loadClass(Unknown Source)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.ClassLoader.loadClass(Unknown Source)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.ClassLoader.loadClass(Unknown Source)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.ClassLoader.loadClass(Unknown Source)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.net.URLClassLoader.findClass(Unknown Source)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.security.AccessController.doPrivileged(Native Method)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.net.URLClassLoader$1.run(Unknown Source)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.net.URLClassLoader$1.run(Unknown Source)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: com.mojang.realmsclient.util.Pair
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    ... 6 more
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:126)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at me.superckl.biometweaker.core.BiomeTweakerCallHook.call(BiomeTweakerCallHook.java:22)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at me.superckl.biometweaker.core.BiomeTweakerCallHook.call(BiomeTweakerCallHook.java:63)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at me.superckl.biometweaker.config.Config.init(Config.java:64)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at me.superckl.biometweaker.script.ScriptParser.parseScriptFile(ScriptParser.java:64)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at me.superckl.biometweaker.script.ScriptHandler.parse(ScriptHandler.java:56)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at me.superckl.biometweaker.script.object.ScriptObject.handleCall(ScriptObject.java:52)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at me.superckl.biometweaker.script.util.ParameterWrapper.parseArgs(ParameterWrapper.java:39)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NoClassDefFoundError: com/mojang/realmsclient/util/Pair
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.reflect.Method.invoke(Unknown Source)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
12.06 02:21:38 [Server] main/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12.06 02:21:38 [Server] INFO A problem occurred running the Server launcher.[02:21:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
12.06 02:21:38 [Server] main/INFO [BiomeTweakerCore]: Sucessfully patched net.minecraft.world.biome.BiomeGenBase! 14 patches were applied.
12.06 02:21:38 [Server] main/INFO [BiomeTweakerCore]: Attempting to patch class net.minecraft.world.biome.BiomeGenBase...
12.06 02:21:38 [Server] main/INFO [BiomeTweakerCore]: Beginning early script parsing...
12.06 02:21:38 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
12.06 02:21:37 [Server] main/INFO [STDOUT]: [cofh.asm.CoFHAccessTransformer:readMappingFile:40]: Adding Accesstransformer map: CoFH_at.cfg
12.06 02:21:37 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
12.06 02:21:37 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
12.06 02:21:37 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
12.06 02:21:37 [Server] main/INFO [TI Transformer]: Chunk: apx
12.06 02:21:37 [Server] main/INFO [TI Transformer]: Access: ahl
12.06 02:21:37 [Server] main/INFO [TI Transformer]: World: ahb
12.06 02:21:37 [Server] main/INFO [TI Transformer]: Block: aji
12.06 02:21:37 [Server] main/INFO [TI Transformer]: Thaumic Infusion has detected an Obfuscated environment!
12.06 02:21:37 [Server] main/INFO [TI Transformer]: Class Transformer starting!
12.06 02:21:37 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
12.06 02:21:37 [Server] main/INFO [STDERR]: [thaumcraft.codechicken.core.launch.DepLoader$DepLoadInst:checkExisting:459]: Warning: version of bspkrsCore, 6.16 is newer than request 6.15
12.06 02:21:37 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
12.06 02:21:37 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
12.06 02:21:37 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
12.06 02:21:37 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
12.06 02:21:37 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
12.06 02:21:37 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
12.06 02:21:37 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
12.06 02:21:37 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
12.06 02:21:37 [Server] main/INFO [FML]: AMCore >> Located Thaumcraft
12.06 02:21:37 [Server] main/INFO [FML]: AMCore >> Located Thaumcraft
12.06 02:21:37 [Server] main/INFO [FML]: MC located at: /.
12.06 02:21:37 [Server] INFO at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [Mod_Forge_1.7.10-10.13.2.1230.jar:?]
12.06 02:21:37 [Server] INFO at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [Mod_Forge_1.7.10-10.13.2.1230.jar:?]
12.06 02:21:37 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_51]
12.06 02:21:37 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_51]
12.06 02:21:37 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_51]
12.06 02:21:37 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_51]
12.06 02:21:37 [Server] INFO at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
12.06 02:21:37 [Server] INFO at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
12.06 02:21:37 [Server] INFO at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:101) [Mod_Forge_1.7.10-10.13.2.1230.jar:?]
12.06 02:21:37 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.11.jar:?]
12.06 02:21:37 [Server] INFO at java.lang.Class.newInstance(Unknown Source) ~[?:1.7.0_51]
12.06 02:21:37 [Server] INFO at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.7.0_51]
12.06 02:21:37 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.7.0_51]
12.06 02:21:37 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.7.0_51]
12.06 02:21:37 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_51]
12.06 02:21:37 [Server] INFO at am2.preloader.AccessTransformers.<init>(AccessTransformers.java:10) ~[AccessTransformers.class:?]
12.06 02:21:37 [Server] INFO at cpw.mods.fml.common.asm.transformers.AccessTransformer.<init>(AccessTransformer.java:101) ~[Mod_Forge_1.7.10-10.13.2.1230.jar:?]
12.06 02:21:37 [Server] INFO at cpw.mods.fml.common.asm.transformers.AccessTransformer.readMapFile(AccessTransformer.java:118) ~[Mod_Forge_1.7.10-10.13.2.1230.jar:?]
12.06 02:21:37 [Server] INFO at com.google.common.io.Resources.getResource(Resources.java:229) ~[minecraft_server.1.7.10.jar:?]
12.06 02:21:37 [Server] INFO at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148) ~[minecraft_server.1.7.10.jar:?]
12.06 02:21:37 [Server] INFO java.lang.IllegalArgumentException: resource AM2_at.cfg not found.
12.06 02:21:37 [Server] main/ERROR [LaunchWrapper]: A critical problem occurred registering the ASM transformer class am2.preloader.AccessTransformers
12.06 02:21:37 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
12.06 02:21:37 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
12.06 02:21:37 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
12.06 02:21:37 [Server] main/INFO [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
12.06 02:21:36 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
12.06 02:21:36 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
12.06 02:21:36 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
12.06 02:21:36 [Server] main/INFO [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
12.06 02:21:36 [Server] main/INFO [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
12.06 02:21:36 [Server] main/WARN [FML]: The coremod thaumic.tinkerer.preloader.ThaumicTLoaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
12.06 02:21:36 [Server] main/WARN [FML]: The coremod thaumcraft.codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
12.06 02:21:36 [Server] main/WARN [FML]: The coremod lumien.randomthings.Transformer.RTLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
12.06 02:21:36 [Server] main/WARN [FML]: The coremod lumien.perfectspawn.Transformer.PSLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
12.06 02:21:36 [Server] main/WARN [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
12.06 02:21:36 [Server] main/WARN [FML]: The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
12.06 02:21:36 [Server] main/WARN [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
12.06 02:21:36 [Server] main/WARN [FML]: The coremod fastcraft.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
12.06 02:21:36 [Server] main/WARN [FML]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
12.06 02:21:36 [Server] main/INFO [STDERR]: [codechicken.core.launch.DepLoader$DepLoadInst:checkExisting:436]: Warning: version of bspkrsCore, 6.16 is newer than request 6.15
12.06 02:21:36 [Server] main/WARN [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
12.06 02:21:35 [Server] main/WARN [FML]: The coremod me.guichaguri.betterfps.BetterFps does not have a MCVersion annotation, it may cause issues with this version of Minecraft
12.06 02:21:35 [Server] main/INFO [FML]: AMCore initializing...stand back!  I'm going to try MAGIC!
12.06 02:21:35 [Server] main/WARN [FML]: The coremod am2.preloader.AM2PreloaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
12.06 02:21:35 [Server] main/WARN [FML]: The coremod mods.battlegear2.coremod.BattlegearLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
12.06 02:21:35 [Server] main/INFO [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.7.0_51, running on Linux:amd64:2.6.18-400.1.1.el5, installed at /usr/java/jre1.7.0_51
12.06 02:21:35 [Server] main/INFO [FML]: Forge Mod Loader version 7.10.85.1230 for Minecraft 1.7.10 loading
12.06 02:21:34 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
12.06 02:21:34 [Server] main/INFO [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
12.06 02:21:34 [Server] main/INFO [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
12.06 02:21:33 [Multicraft] Loaded config for "Forge 1.7.10-Recommended (v10.13.2.1230)"
12.06 02:21:32 [Multicraft] Starting server!

**Comment by DrasticDemise** [comment]
Currently server files aren't supported. There are mods that are client side only and are not removed. It also looks like you downloaded forge version 1230 when the pack uses 1455.
