### ISSUE TITLE
AM UI

### ISSUE THREAD

**Issue by Schist-** [DrasticDemiseFTBPacks/Banished#28]
By default the mana and burnout bars cover the Mine & Blade bar, it'd be nice if they were moved since every update causes them to be reset to the default position. Obviously not a major issue but it'd be kinda nice.

**Comment by 0Bheka0** [comment]
just note the use of /amuicfg in the quests alternatively.

**Comment by DrasticDemise** [comment]
This is a resolution specific issue. I will note it in the quest book, players will ahve to change it themselves.
