### ISSUE TITLE
Issue: Infinite Water

### ISSUE THREAD

**Issue by 0Bheka0** [DrasticDemiseFTBPacks/Banished#30]
Something seems to disable water source regeneration as of 0.6.0 making progressing in Botania very strange due to the lack of large source collections like lakes or such.

**Comment by Mechalith** [comment]
This may not be a matter of source generation. I've noticed that after about 15 minutes or so, something is freezing the server side of Minecraft, stopping anything from dropping items and freezing mobs and fluids. Almost certain it's related to the Epic Siege issues. Still testing to see if new version is working properly.

**Comment by DrasticDemise** [comment]
This is intended. Water is set to finite, you can get more by finding it or the spell that is given to you.
