### ISSUE TITLE
Soulbound items disappear after death

### ISSUE THREAD

**Issue by EliteThree** [DrasticDemiseFTBPacks/Banished#32]
The items enchanted with soulbound were not given back to me when I died, specifically my spellbook.
I was killed. I quit the game without respawning. Reopened the game. Clicked respawn. No items :cry: 

Probably not something you can fix but maybe a workaround is possible?

**Comment by EliteThree** [comment]
Apparently my entire AM2 progress was reset as well? I just got a new spell and my mana/levels are back to 1.

**Comment by Mechalith** [comment]
Sounds like something ate your save data somehow. Did it reset anything else?

**Comment by DrasticDemise** [comment]
Also, were they in your grave?

**Comment by EliteThree** [comment]
They were not in my grave and I didnt touch my player data. I am thourougly puzzled.

**Comment by EliteThree** [comment]
As a side note is there a command to manually change my am2 level to get back to were I was?

**Comment by DrasticDemise** [comment]
Not much I can do, AM2 has so many bugs. Try to reproduce it and if you manage to have it happen again, open up another issue. Thanks for the report.
