### ISSUE TITLE
Very few hostile mobs spawning

### ISSUE THREAD

**Issue by Mechalith** [DrasticDemiseFTBPacks/Banished#33]
Anyone else had issues with this? I have an extremely difficult time finding any mobs (except lava monsters), and most of the time when I do find one on my radar and get close to it, the thing bails or despawns. Even digging out an intentional mob spawner doesn't get me any mobs most of the time. Bafflingly, creepers are especially prone to seeing me pop out of a wall and then getting out of range as quick as they can.

I've disabled the Wild Caves mod, which seems to help a bit, but spawn rate is still pretty low. I've also run Opis and at least some of the time, it seems like the majority of the mobs it detects are in the Overworld still and not the Caveworld. Resetting the world spawn point to the Caveworld appears to have helped that at least.

I expected the main difficulty in the pack to be fending off the swarms of monsters thirsting for my blood and instead it's mainly been difficulty in finding enough critters to fuel my Dark Power and progress through the quests.

**Comment by DrasticDemise** [comment]
Since you updated ESM I may need to adjust the defaults to compensate, but this is definitely an issue. Thanks.

**Comment by 0Bheka0** [comment]
In my experience ironically it is not the problem that there are not enough mobs but that they simply cannot get to you even with the Siege mod providing advanced mobility. There are just not enough diamond pick zombies furiously tunneling towards you to get every spawncluster in range.

**Comment by DrasticDemise** [comment]
There is a set amount of warm up days before they spawn non-stop. The default is set to 7, so when 7 minecraft days pass their spawn rate is supposed to be greatly increased.

**Comment by Mechalith** [comment]
I've actually turned off the warm up period in the cfg, set the difficulty to hard and created a new world, still next to nothing. I found a sinister node that was horfing out furious zombies every minute or so, but virtually no random spawns.

**Comment by DrasticDemise** [comment]
It could actually be my biome tweaker script capping the mobs. Let me mess around with that a bit

**Comment by DrasticDemise** [comment]
That seems to have upped the spawning from about 88 mobs at a time to 160 in a quick test. Still doesn't seem to be enough though.

**Comment by DrasticDemise** [comment]
Update is pushed. Should increase the amount of mobs to a reasonable amount. Open another thread if issue persists.
