### ISSUE TITLE
caveworld biomes

### ISSUE THREAD

**Issue by Turmfalke2** [DrasticDemiseFTBPacks/Banished#34]
hi,
I think the caveworld shouldn't be using the normal vanilla biomes. Give that there is no real surface, you can end up spawning in the surface blocks of the biome.
For example I just created a new world and it spawned my portal in a mesa biome. There is only hardened clay, no stone and with that no ores at all. I am not sure whether there would be stone if I dig deep enough, because digging is kind of difficult right now.

**Comment by EliteThree** [comment]
You just need to explore or dig until you get to a new biome, they arent too big.

**Comment by DrasticDemise** [comment]
There are ores in the mesa biomes. They are set to spawn in place of hardened clay. The biome size is set fairly small, running around a bit should get you in another biome. It is meant to bring variety to a dull cave world.
