### ISSUE TITLE
spectres dimension

### ISSUE THREAD

**Issue by Turmfalke2** [DrasticDemiseFTBPacks/Banished#37]
hi,
I crafted a key for the spectre dimension, but it bugged out horribly.
When I first used it, it moved me(I think in the new dimension), but the world didn't load. So tried to leave the world back to the main menu. The game then got stuck at trying to logout for about 5 minutes. I killed the process, restarted minecraft and spawned in the caveworld in the middle of a wall.
Using /gamemode c I freed my self and teleported my self back to my base, but now when ever I use the key it teleports me back in that wall in the cave world instead of the spectre dimension.

**Comment by Mechalith** [comment]
This actually happens with any dimensional transition I've tried. Attempting to jump to the Nether will do the same thing. I assume it's a quirk of the Caveworld dimension or something that DrasticDemise added to prevent monkeying about in other dimensions.

**Comment by DrasticDemise** [comment]
You aren't meant to switch dimensions. I will nub-proof this and remove the key and disable portal creations. Thanks.
