### ISSUE TITLE
mob spawning

### ISSUE THREAD

**Issue by Turmfalke2** [DrasticDemiseFTBPacks/Banished#38]
hi,
Played for a few hours and noticed something about mob spawning.
I have never seen even a single spider - not even on the minimap.
Creepers do spawn, but they always directly blow up before I can even get line of sight on them.

This makes some quests impossible to complete.

**Comment by DrasticDemise** [comment]
Hmm. Will see what I can do about that.

**Comment by DrasticDemise** [comment]
What if I added a cost of Dark power 1-1 string

**Comment by Turmfalke2** [comment]
I would prefer spiders spawning, instead of the string quest. Is there any other way to get string besides cobwebs?

**Comment by Mechalith** [comment]
You can get it from the puffball flowers, and IIRC you can transmute wool back into string w/ Botania.

EE3 can transmute it as well, once you get to that point.

**Comment by DrasticDemise** [comment]
You will find plenty of mobs now :) You just wait.
