### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Turmfalke2** [DrasticDemiseFTBPacks/Banished#4]
hi, I haven't really done anything, but I already experience some performance issues.
What I have done:
Before creating the world, I have set the render distance to 3.
After creating the world and having the first look into the questbook (had to manual enable /hqm questing) I noticed I had to break the 2 chests several times to actually pick them up.
I then stepped through the portal, creating the world took quite a bit of time, but that is fine.
After that I gave minecraft another minute or so catch up, but even after that my console is still getting spammed with:
[Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 196045ms behind, skipping 3920 tick(s)
Using /cofh tps I have noticed that the tps in the caveworld keeps jumping between 7 and 18 and this is quite noticeable when mining cobble for the first quest.
The fps periodically drop to around 20 from their normal 60.
I haven't really moved away from the portal and I can't see anything special, there is only a bit of lava nearby.

**Comment by FranklinShack** [comment]
Yes, I have noticed too. Also, when moving away from the portal, I get a ton of lag spikes, and then when I exit the world, the game crashes, and when I load in, the world is about 2 minutes behind, as in I spawned where I was 2 minutes ago.

**Comment by DrasticDemise** [comment]
Does the minimap notice many squid? It may be a ton of squid spawning and despawning.

**Comment by FranklinShack** [comment]
Yeah actually, there are tons of squids for no reason

**Comment by DrasticDemise** [comment]
Ah. I will have to install Squidless. That could easily be tearing up the game. If you want, try installing squidless and see if it improves.

**Comment by FranklinShack** [comment]
Alright, where can I find it?

**Comment by DrasticDemise** [comment]
http://www.curse.com/mc-mods/minecraft/226115-squidless

**Comment by DrasticDemise** [comment]
Also try disabling the radar on Journeymap in the J settings to see if that helps.

**Comment by FranklinShack** [comment]
Ok, thanks!

**Comment by Turmfalke2** [comment]
I can only see 1 or 2 squids on the minimap and they don't seem to despawn/respawn. Going to try disabling that radar.

**Comment by MojiRS** [comment]
Just tried installing Squidless and disabling radar, but it seems to have had minimal effect. However, changing the difficulty to peaceful solves the problem entirely, so the problem seems to have something to do with mob spawning or the mobs themselves.

**Comment by FranklinShack** [comment]
perhaps it has something to do with the epic siege mod? The mining zombies leave behind a LOT of items on the ground

**Comment by MojiRS** [comment]
oh, that wouldn't surprise me at all

**Comment by FranklinShack** [comment]
Yeah, that seems like the most obvious thing that would cause lag

**Comment by DrasticDemise** [comment]
Their AI is usually pretty intensive, but I honestly think something is rapidly spawning an despawning. 

You can delete all mobs/blocks near you with /cofh killall *

**Comment by FranklinShack** [comment]
Hmm, I'll haev to try that

**Comment by MojiRS** [comment]
huh, just tried doing /gamerule doTileDrops false and /cofh killall, and it doesn't seem to help

**Comment by MojiRS** [comment]
not sure what the problem is

**Comment by FranklinShack** [comment]
Must be something else then

**Comment by DrasticDemise** [comment]
Go into creative and sit there for a bit to see if it gets better. It could still be the liquids and falling blocks spawning in chunks around you.

**Comment by FranklinShack** [comment]
Maybe

**Comment by DrasticDemise** [comment]
I don't get a major FPS drop from my usual when I spawn a new world, so this could be a world specific issue.

**Comment by MojiRS** [comment]
no, it definitely has to do with the mobs - changing the difficulty to peaceful solves the problem entirely

**Comment by DrasticDemise** [comment]
Ah right

**Comment by DrasticDemise** [comment]
Xray mobs could cause an FPS drop since every mobs is being processed additionally respective to the player.

**Comment by Turmfalke2** [comment]
I keep hearing explosions in the distance. Could they be related?

**Comment by FranklinShack** [comment]
Yeah, those explosions are annoying

**Comment by DrasticDemise** [comment]
That is the creepers tunneling to you, which can cause blocks on the ground.

**Comment by MojiRS** [comment]
well, it definitely has to do with the epic siege mod. uninstalling it solves the problem as well

**Comment by DrasticDemise** [comment]
I disabled Xray mobs and disabled more spawning. That should help a bit.

**Comment by MojiRS** [comment]
if we update the modpack, will we get those changes? is that what you mean?

**Comment by DrasticDemise** [comment]
Nope, it will be changed in the next update which I will release tonight to clean up some things

**Comment by DrasticDemise** [comment]
But you can make those changes yourself in the ESM config file

**Comment by MojiRS** [comment]
oh, alright

**Comment by MojiRS** [comment]
yep, that seems to have fixed it!

**Comment by DrasticDemise** [comment]
_fingers crossed_ 

Can someone else make these config changes as well?

**Comment by Woif1990** [comment]
Trying those changes now.

**Comment by MojiRS** [comment]
that's what i meant - i tried the config changes, and they solve the problem!

**Comment by MojiRS** [comment]
oh wait, did you mean someone in addition to me?

**Comment by DrasticDemise** [comment]
Yeah

**Comment by Woif1990** [comment]
No real change for me. If anything it may have gotten worse.

**Comment by DrasticDemise** [comment]
I am releasing a patch soon that should fix up some performance issues.

**Comment by Turmfalke2** [comment]
now on version 0.4?
I am still getting like 5 tps and below 40 fps.
With nothing special going on.

**Comment by Turmfalke2** [comment]
Even after changing the gamemode to peaceful /cofh killall \* reports:
Removed 851 entities. (143 Thaumcraft.AspectOrb, 25 Spider, 213 Item, 9 LavaMonsters.LavaMonster, 2 Chicken, 36 Skeleton, 9 Cow, 5 Slime, 20 Squid, 9 Caveman, 36 Zombie, 2 MinecartTNT, 67 Sheep,154 arsmagica2.MobDryad, 3 arsmagica2.Flicker, 9 ArcherZombie, 6 Pig, 1 Thaumcraft.Pech, 16 Blaze, 10 Enderman, 36 Bat, 40 Creeper)]

**Comment by Turmfalke2** [comment]
After playing 20 minutes on peaceful /cofh killall \* reports:
Removed 1034 entities. (192 Thaumcraft.AspectOrb, 25 Spider, 285 Item, 35 LavaMonsters.LavaMonste, 2 Chicken, 36 Skeleton, 8 Cow, 5 Slime, 22 Squid, 4 Caveman, 34 Zombie, 1 MinecartTNT, 65 Sheep, 203 arsmagica2.MobDryad, 3 arsmagica2.Flicker, 9 ArcherZombie, 5 Pig, 1 Thaumcraft.Pech, 16 Blaze, 8 Enderman, 40 Bat, 35 Creeper)

While playing on peaceful with normal tps is possible, I feel like this is not a solution since hqm progression requires killing monsters.

**Comment by DrasticDemise** [comment]
Those dryads and items on the ground are my next target. Dryads don't despawn (And I don't know why the heck they spawn under ground anyway) so they will be disabled. 

I am also going to see if I can disable some creepers from randomly exploding since they are causing items all over the floor.

**Comment by 0Bheka0** [comment]
If you are disabling dryads you'd need to introduce some way to spawn them or the nature guardian though so AM2 nature essence as well as the badass scythe can still be obtained.

**Comment by DrasticDemise** [comment]
Gideon confirmed that the TPS bog down is from Epic Siege Mod. I have tested his configs and they seem to solve the TPS issue if not help it a ton. Changes will be made in 0.0.5

**Comment by Mechalith** [comment]
I've just tested, and in a brand new world, immediately after stepping through the portal a /cofh killall nuked 161 mobs. A second, approximately 60 sec later, produced 94. I think part of the problem might just be the spawn rate combined with the 64 block sensing range that the Epic Siege Mod gives them.

**Comment by Mechalith** [comment]
Also, don't know if Xray mobs being set to false should have stopped it, but I'm still getting immediate creeper blasts in the distance trying to bore their way toward me.

**Comment by DrasticDemise** [comment]
I will be turning Xray off again (It was on this update) and slashing the awareness from 64 to 32. I am also disabling creeper griefing so they should no longer cause blocks to drop.

**Comment by Mechalith** [comment]
I also just noticed that the Lava Monster mod is checking to spawn about 3x per second which likely isn't helping, especially if the Siege Mod is trying to apply it's enhanced AI to them.

**Comment by 0Bheka0** [comment]
It should be 2 times per second as the config has 
   "# The number of ticks between each lava monster spawn attempt.
    I:spawn_frequency=10"
This should maybe be increased if their spawn process is more CPU intensive than standard spawning.

**Comment by Mechalith** [comment]
After a bit of testing: doesn't look like they have any impact on performance. I disabled them entirely and it made no difference.

**Comment by Mechalith** [comment]
Currently giving the 10.0.112 build of ESM a shot to see if it improves things.

**Comment by Mechalith** [comment]
112 appears to help a great deal, but it also seems to have somehow disabled the ability to set your spawn point with a bed.

**Comment by DrasticDemise** [comment]
You probably have to enable sleeping in the config. It is disabled by default

**Comment by Mechalith** [comment]
I'm using the same config file that was allowing me to sleep in 106. Tried deleting the .cfg, regenerating it and then updating the settings to allow sleep, still doesn't work.

**Comment by Mechalith** [comment]
OK, found the problem. It's weirder than I thought though. At least in ver. 112, ESM creates a file in each new world with it's default config values is in (NOT the ones you've set manually in ESM.cfg). Unless you have "Enforce Defaults" set to false, it uses that world-specific config file, which contains the default values of the mod, which means that it's set to disallow sleep, awareness radius of 64, xray mode turned on, etc.

I'll have to roll back my install to double check this, but I think that the reason switching xray mode off, etc have had limited effect is that "Enforce Defaults" was set to true, meaning all the changes Drastic made didn't actually update squat in the file the mod was actually using. (Among other things, that explains why the creepers never stopped trying to blast their way through to me immediately on spawning into the map.) Checking, will update shortly.

**Comment by Mechalith** [comment]
Confirmed that Banished 0.0.5 has the world config set to Xray=true, sleep disabled, etc. Extra fun: ESM didn't have the option to not use that file in version .106, so as far as I can tell the main ESM.cfg file was actually useless except as a reference. Moving back to Banished 0.0.6 for further comparison.

**Comment by Mechalith** [comment]
Confirmed, settings were the same in 0.0.6, although at least some of them must have respected ESM.cfg because the beds worked, even though the mobs were clearly still in Xray mode in direct contradiction to it.

At any rate, have updated back to ESM 10.0.112 and updated ESM.cfg to Enforce Defaults=False and the rest of the settings to current pack default (awareness 32, xray off, etc.) and it seems to overall have much better performance. Because of the small handful of changes, you do need to delete and re-create the ESM.cfg though, or it won't have the Enforce Defaults parameter in there.  (Could probably edit it manually, but there's the risk of syntax errors and such, generally not worth the bother.)

**Comment by DrasticDemise** [comment]
Alright, I will update it and redo the configs.

**Comment by Mechalith** [comment]
Make sure you don't forget the config in the template folder. (I did, not sure if it was causing any problems, but it certainly could.)

**Comment by DrasticDemise** [comment]
Have you run into any tps issues since?

**Comment by Mechalith** [comment]
The occasional hiccup still, but it's substantially less common. I have noticed that I get remarkably few mobs spawning though. Even when I intentionally leave large areas unlit, I have to go actively hunting for monsters to find anything. (This has been the case even before I updated ESM though.)

**Comment by Turmfalke2** [comment]
not sure whether we should have a new issue or just add to this one. using the v6 I am still getting tps drops:

[01:36:50] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 47610ms behind, skipping 952 tick(s)
That is almost a minute of nothing happening.

E:
 [01:48:05] [Client thread/INFO]: [CHAT] Overall: 1,35 TPS/742,21MS (6%) 
[01:48:05] [Client thread/INFO]: [CHAT] Overworld [0]: 20,00 TPS/0,08MS (100%) 
[01:48:05] [Client thread/INFO]: [CHAT] Nether [-1]: 20,00 TPS/0,02MS (100%) 
[01:48:05] [Client thread/INFO]: [CHAT] The End [1]: 20,00 TPS/0,01MS (100%) 
[01:48:05] [Client thread/INFO]: [CHAT] Aqua Caveworld [-10]: 20,00 TPS/0,05MS (100%) 
[01:48:05] [Client thread/INFO]: [CHAT] The Outer Lands [-42]: 20,00 TPS/0,02MS (100%) 
[01:48:05] [Client thread/INFO]: [CHAT] Bedrock [-19]: 20,00 TPS/0,02MS (100%) 
[01:48:05] [Client thread/INFO]: [CHAT] SpectreWorld [2]: 20,00 TPS/0,01MS (100%) 
[01:48:05] [Client thread/INFO]: [CHAT] Caveworld [-5]: 1,36 TPS/736,86MS (6%) 
[01:48:05] [Client thread/INFO]: [CHAT] Deep Caveworld [-6]: 20,00 TPS/0,04MS (100%) 
[01:48:06] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 70657ms behind, skipping 1413 tick(s)

I feel like it is worse than before with v6

**Comment by DrasticDemise** [comment]
The latest of version should fix these TPS drops. Hold out for the next update which should be soon.

**Comment by DrasticDemise** [comment]
Update has been pushed. Should solve performance issues. If you continue to have massive TPS drops, open another issue.
