### ISSUE TITLE
Can't find a source of clay

### ISSUE THREAD

**Issue by Mechalith** [DrasticDemiseFTBPacks/Banished#40]
Just what it says. IS there one?

Additionally, can't find a source of Netherrack or quartz. Is there a Nether biome I'm just not finding?

**Comment by DrasticDemise** [comment]
There are nether biomes around they are just a bit more rare. I will add clay pockets, but I think other mods have a recipe for it.

**Comment by Mechalith** [comment]
There isn't currently a recipe in NEI at the very least.

**Comment by DrasticDemise** [comment]
What are you making that needs clay?

**Comment by Mechalith** [comment]
EE3 chalk block. (While we're on the subject, there doesn't appear to be a recipe to make a stick of EE3 chalk.)

**Comment by DrasticDemise** [comment]
The EE3 chalk comes from breaking the chalk block. You can get clay with the clayconia, but I think to make it you need clay. Hmm. Will fix.

**Comment by DrasticDemise** [comment]
There are now clay veins found in stone, grass, and hardened clay.
