### ISSUE TITLE
Umber Lobber spawning continuously.

### ISSUE THREAD

**Issue by Mechalith** [DrasticDemiseFTBPacks/Banished#43]
Giant freakin' lava monster, spawns almost upon the death of the previous one. I've had a total of 6 so far, which wouldn't be as much of a problem, but they generate lava around them and the waterfalls in the big lava lake cause an absurd amount of block updates.

This is (probably) an issue with Lycanite's mod and not your pack, but you may want to set the cfg to disable the 'lobbers melt blocks' option to prevent it being as much of an issue.

**Comment by DrasticDemise** [comment]
Any issues with other lycanites or their spawn rates? I am taking on the balancing act with this mod since it can seem over powering. I will also be adding in dark power for killing some of the mobs.

**Comment by DrasticDemise** [comment]
Actually lets move this to a discussion thread. I have disabled block melting.
