### ISSUE TITLE
Spelling Issues

### ISSUE THREAD

**Issue by ConfigsPlease** [DrasticDemiseFTBPacks/Banished#47]
I'm opening this to note spelling errors/grammatical errors that I find throughout the questbook.

To start - Under "Mystical Constructs" on the Survival quest tree, the quest description lists different base blocks for the golems. It has the word "brikc" instead of brick, about halfway through.

**Comment by ConfigsPlease** [comment]
I just realized this should probably go into "quest suggestions / feedback" - my bad. Feel free to close it if you want the spelling stuff there instead.

**Comment by DrasticDemise** [comment]
Resolved.
