### ISSUE TITLE
Dark Power Reward Suggestions/Feedback

### ISSUE THREAD

**Issue by DrasticDemise** [DrasticDemiseFTBPacks/Banished#49]
Any suggestions or feedback pertaining to rewards or obtaining methods. Can range from items to custom Am2 spells that you provide below.

**Comment by Mechalith** [comment]
The shade and the grues are sometimes very inconsistent as to whether they count for the dark power quests. I'm aware they require more than one to complete, but they aren't always incrementing the 'X out of X killed' tracking in the quest. I've got no idea why, or which specific variant mobs do and don't count, unfortunately. I'll update this when/if I find a pattern.

Also, it might be desirable to remove the shade-spawning-from-your-bed scripting, otherwise someone could potentially use their bed as a mob spawner.

**Comment by DrasticDemise** [comment]
Are the subspecies mobs not counting such as the Azure or lunar? I also don't believe there is a config to disable that. I have peeked in the shadow mobs and general config for it. If you find it, let me know.

**Comment by Mechalith** [comment]
I don't know what is controlling it, but it's not the sub-species causing trouble, I've seen a plain old Grue not count as well.

**Comment by FranklinShack** [comment]
I think that the Lycanites dark power quests should also have a timer because it becomes incredibly easy to farm Afrits by sitting by a lava pool and hitting them with Magic Beam continuously, and as the quest doesn't have a cool down, nearly infinite dark power relatively early game

**Comment by DrasticDemise** [comment]
Uhh, they do have a cool down. Does that particular quest not?

**Comment by FranklinShack** [comment]
If there is a cool down, it isn't noticeable, as I just sat a lava pool and kept killing the lobbers and afrits which spawned, completed the quests, and did it again.

Although this may be a bug, as I was testing with the OP quesstbook and when I used the complete function, it did show a cooldown.

**Comment by DrasticDemise** [comment]
I have moved them from Resets on Interval to Cooldown on Completion. While I am not entirely sure, I have a feeling that monsters not counting is due to the reset on interval kicking in mid-way through quest progress and resetting it(if that is how it works). This should also put a hard cap on the cool down.

**Comment by Mechalith** [comment]
I've actually given myself a stack of Grue spawn eggs and mauled several of them. As far as I can tell, none of the Grue types count for the kill quest. Lunar, Crimson, Just-Plain-Grue, etc. I've used spells and sword, both have the same result. Has anyone else had this problem, or am I just 'special'?

**Comment by DrasticDemise** [comment]
That would be because I forgot to set a monster there the entire time. Who knew?
