### ISSUE TITLE
0.0.13

### ISSUE THREAD

**Issue by DrasticDemise** [DrasticDemiseFTBPacks/Banished#52]
- Rose bush script
- Nerfed wisp spawn rate, buffed zombie.
- Fixed sleeping
- Mobs no long grief lights, and blocks they grief no longer drop. 
- Thaumcraft special nodes are now a bit more rare. Significant TPS improvement. 
- Added the base to thaumcraft quests, though these are not accessible yet.
- Removed dark menagerie.
- Removed some useless lycanites mobs.

**Comment by Mechalith** [comment]
Might want to update the custom startup page, currently it recommends disabling ESM to improve performance, which will be tricky since it isn't in the pack anymore. ;)

**Comment by Mechalith** [comment]
Also, looks like you left OPIS enabled, so the mapwriter minimap is showing atop Journeymap.
