### ISSUE TITLE
Version 0.0.14 - Final testing phase

### ISSUE THREAD

**Issue by DrasticDemise** [DrasticDemiseFTBPacks/Banished#53]
- Vanilla mobs are back! Thanks for nothing Lycanites.
- Thaumcraft quests now finished.
- Added the rest of the AM2 bosses
- Server helper item for HQM rep resets.
- Updated thaumic infusions - should help performance

This is hopefully the last testing phase before final release. Thank you everyone who has stuck around, I cannot thank you enough. Except maybe in a tiny potato quest reward in the botania line...

**Comment by Mechalith** [comment]
Always glad to help with this sort of thing. Thanks for not getting sick of seeing my issue reports. =P

**Comment by FranklinShack** [comment]
Glad to help, thanks for letting me :)
