### ISSUE TITLE
Issue: Colossus Class Utility Mobs

### ISSUE THREAD

**Issue by 0Bheka0** [DrasticDemiseFTBPacks/Banished#54]
Colossus golems from Utility Mobs do not form at all.

**Comment by DrasticDemise** [comment]
I am not finding anything called a Colossus golem in the golem manual.

**Comment by Mechalith** [comment]
I'm pretty sure Bheka means this thing: http://fathertoast.wikia.com/wiki/Obsidian_Colossus

**Comment by DrasticDemise** [comment]
I was able to create it just fine. Can you provide a screenshot of the build?
