### ISSUE TITLE
Suggestion: Kickstart Quests for AM2 Flicker system

### ISSUE THREAD

**Issue by 0Bheka0** [DrasticDemiseFTBPacks/Banished#56]
As it is a very versatile system giving a habitat, import, export crystal for crafting a flicker lure would give some incentive. Alternatively Botania Corporea system could be kickstarted similarly. Or both.

**Comment by Mechalith** [comment]
I'm not sure it's currently possible to use the Corporea system, as it requires a bottle of Ender Air for a number of the components.

**Comment by DrasticDemise** [comment]
You can create ender air bottles through aura cascade. And I will be using the Aura Cascade storage quest line as my storage choice this pack instead of the corporea system
