### ISSUE TITLE
Nether quartz crash warning

### ISSUE THREAD

**Issue by Mechalith** [DrasticDemiseFTBPacks/Banished#59]
Using the AOE enchant on a Silent's Gems pick or using any of the AM2 dig spells on or near nether quartz causes an immediate client crash to desktop. I'm not sure if the Thaumcraft excavation focus has the same problem, I haven't made one yet. Not sure if this is due to something in the mods or an interaction with Nether Ores or what, I'll be testing to see.

I didn't report this earlier because I thought it was just AM2 doing it, and since the mod is notoriously bug riddled I assumed it fell into the category of 'can't fix, Someone Elses Problem.' I'll update this if/when I hunt down the cause.

**Comment by DrasticDemise** [comment]
I assume it is a ticking entity crash as I received one randomly due to nether quartz. Can I get the crash log in a paste bin?

**Comment by DrasticDemise** [comment]
Actually I have the crash log through yampst and was able to reproduce it. I will forward this to the silent gems dev.

**Comment by Mechalith** [comment]
http://pastebin.com/U4R4LgxL

**Comment by Mechalith** [comment]
I've confirmed: it's a problem with the Nether Ores mod. Not sure why it only affects the quartz, but I've disabled the mod for testing and now AM2 and Silent's both work fine. 

Simply disabling the explosions in the cfg didn't have any effect, but I still think that the test for whether the crystal ignites is the root of the problem.

**Comment by DrasticDemise** [comment]
Interestingly enough using the AOE tools in creative isn't a problem, and they will even ignite and explode just fine, it is when they drop to the ground.

**Comment by DrasticDemise** [comment]
Nether ores removed.
