### ISSUE TITLE
Need a source of cows/milk

### ISSUE THREAD

**Issue by Mechalith** [DrasticDemiseFTBPacks/Banished#60]
I haven't seen any passive spawns naturally occur, and you need to be able to get milk for certain recipes. (Winter runes from Botania require cake, for instance.)

I'd recommend some kind of vortex infusion recipe for the farm animal spawn eggs. Maybe a seed and 3 leather for a cow, feathers for chicken, etc?

**Comment by DrasticDemise** [comment]
There is a fairy ring that will summon hordes of passive mobs(baiter fairy I think?) and all that requires is 4 eggs and a fairy charm. I may add a dark power reward of an egg.

**Comment by DrasticDemise** [comment]
Added eggs to the dark power quest line. This will set progression of passive mobs through aura cascade as the leader of other mods as intended.
