### ISSUE TITLE
0.0.16 - World restart necessary

### ISSUE THREAD

**Issue by DrasticDemise** [DrasticDemiseFTBPacks/Banished#62]
- Removed Nether Ores. Increase nether quartz and soul sand generation to compensate, as well as added in emerald ore to have the same spawning behaviors as diamond.
- Updated Silent Gems, Journey map, Storage drawers.
- Added Thaumcraft NEI Plugin
- New recipe for End Stone
- Fixed great wood sapling recipe
- Removed Aura crystals quest
- Added in eggs questy
- EMC values added for TC shards, Silent Gems, chisel world gen. Fixed EMC dupe for potions. 
- Thaumcraft text sped up client-side.

This update will require a world restart in order for the EMC values to take effect. OR, you can go into your save folder -> Data. Copy the EE3 folder from a new updated world and replace the old EE3 folder in your current world.

**Comment by Mechalith** [comment]
Somehow varied mob size seems to have been switched back on. Either that or I've just encountered a bunch of huge(er than usual) umber lobbers for some other reason.

Edit: nevermind, it's just a really strangely placed mob, the config is fine.
