### ISSUE TITLE
Aura Cascade suggestions/potential problems

### ISSUE THREAD

**Issue by Mechalith** [DrasticDemiseFTBPacks/Banished#64]
Might want to add a warning note for the Red Hole quest. The blast from it is a lot larger than I thought, and I actually blew up part of my house because I assumed it'd be roughly the same as a creeper/TNT explosion. 

A clearer description of what the Angel Pendant (amulet? can't remember for sure) actually does might also be nice. It's a TON more useful than I initially thought, and I would have made one much sooner if I'd realized.

The Forbidden Fruit amulet quest reward gives you 4 foods, and at least two of them are severe negative effects (10 minutes of Hunger and 8ish minutes of Withering, for the chicken and apple IIRC). I'm not sure if this is an enchantment ID mismatch of some kind or whether it's intentional, but that's a pretty raw quest reward if you did it on purpose, especially given how expensive the item is to make. 4 diamonds, 16 wool, 16 iron ingots, and your reward is a 50% chance you'll kill yourself by accident.

**Comment by DrasticDemise** [comment]
Yeah some of the quest rewards are very much fillers.  I will make sure to change that. Any suggestions for rewards?

**Comment by DrasticDemise** [comment]
This quest has just been removed next update.
