### ISSUE TITLE
Mod Suggestions

### ISSUE THREAD

**Issue by DrasticDemise** [DrasticDemiseFTBPacks/Banished#68]

**Comment by Fortanono** [comment]
Sorry for posting on your thread about this earlier. Couldn't find the right spot. :P

Anyway, in my words from there:

GeoStrata by Reika could work very well, it adds new stone types which generate in patches (unlike Underground Biomes which replaces all stone) and also adds vents that emit smoke, poison and stuff like that. However, you'd need permission (it's not Rotarycraft, it's addons, or ChromatiCraft, so it wouldn't be too hard) and you'd probably need to disable Chisel's granite, marble and limestone from generating in the world, but I think it'd be cool. The vents would also add a bit of challenge.
