### ISSUE TITLE
1.0.1 version game crashed

### ISSUE THREAD

**Issue by kubadr** [DrasticDemiseFTBPacks/Banished#70]
Hello there,

Well, so I started like 3 or 4 worlds in search of good one and when I started the third one I had huge 1 sec lag spikes and couldnt play. In 30 secs my game crashed with out of memory, which is not the "bad" thing, but after that I even got some error which quit my game and didnt let me to try to go back to main menu.

Here are my logs:

Out of memory error: http://pastebin.com/wHAEXq0v

The second error: http://pastebin.com/GyBcupnY

I hope this is everything, if something more is needed I will surely send it too :smile:

**Comment by Mechalith** [comment]
Can you load back into that world now that you've created it? If so, throw in a /cofh killall \* and see how many entities it wipes out.

If it's not insane and the lag is improved (or goes away fairly quickly) then you probably just ran into a problem I get semi-frequently with making multiple new worlds in a short period. I'm not sure if it's a memory leak or a garbage collection problem.

I also had this issue the first time I created a new world with the current version of Optifine installed (which I notice you've got as well) so it may have contributed to the system hork.

**Comment by DrasticDemise** [comment]
You have liteloader mods and Optifine running. Are you also not launching from the FTB launcher? I can only support an unmodified mods list (within reason) and launched off the ftb launcher.

**Comment by kubadr** [comment]
ah srry, will try to duplicate it. Didnt realise that I had few mods added, I just add them automaticaly into packs now.

**Comment by kubadr** [comment]
well, I guess I have to apologise for this report, it probably was caused by optifine as I cannot duplicate it without it :smile: . Anyway, thanks for answering and helping me :)

**Comment by DrasticDemise** [comment]
No worries.
