### ISSUE TITLE
Duplicate crafting recipes

### ISSUE THREAD

**Issue by malaclypse2** [DrasticDemiseFTBPacks/Banished#71]
Caveworld and Silent's Gems both have Aquamarine tools, have the same obvious recipes, and the Aquamarines from each mod are oreDicted together.  That ends up giving the one recipe for two different items.  I think the Caveworld version should probably just be disabled.

**Comment by DrasticDemise** [comment]
What. How are those even ore dict. I will look into it, thanks!

**Comment by DrasticDemise** [comment]
Fixed. Thanks friend!
