### ISSUE TITLE
NEI shows wrong recipe for Greatwood Sapling and Silverwood Sapling

### ISSUE THREAD

**Issue by joakibj** [DrasticDemiseFTBPacks/Banished#72]
http://i.imgur.com/C1C7Ija.png
http://i.imgur.com/BTHDEk2.png

NEI shows 5000 green power requirement for the thaumium ingot and oak sapling. While the Aura Cascade tooltip shows 5000 green power only for the oak sapling (which works).

Same goes for the silverwood sapling except it's only the diamond block that requires 5000 blue power.

**Comment by DrasticDemise** [comment]
None of the mod developers know what could be causing the issue. I hate my life ¯\_(ツ)_/¯
