### ISSUE TITLE
Journeymap buggy/inconsistent

### ISSUE THREAD

**Issue by Mechalith** [DrasticDemiseFTBPacks/Banished#74]
The minimap semi-regularly greys everything out until I change the zoom level. Seems to mainly be a problem with the new version of the map, not really sure what we can do about it other than hope for an update that corrects it or go back to the prior version.

**Comment by DrasticDemise** [comment]
The latest version was supposed to improve cave mapping but I will poke Techbrew about it. The only reason I included Journeymap was as a way to detect mobs and set way points anyway.
