### ISSUE TITLE
1.1.1 still has Caveworld in template folder

### ISSUE THREAD

**Issue by Mechalith** [DrasticDemiseFTBPacks/Banished#76]
See title, really.

**Comment by DrasticDemise** [comment]
I have no idea how that is even possible. The template folder I uploaded has the dim folders for those deleted and I was still randomly spawning when I entered the portal. Are you still getting the same exact world every new world?

**Comment by DrasticDemise** [comment]
Do you delete the world each time you create a new one? Try spamming a random name to see if you get a new spawn, or type in a new seed.

**Comment by Mechalith** [comment]
OK, think I found the problem. The template doesn't have that dim file in it anymore, but the update didn't delete it either. Nuked the whole install folder and re-downloaded, seems to have properly installed without the problematic dimension folders this time.

I'm wondering if this might also explain some of the mis-matched results we've had in previous phases of testing, where you'd get one thing and I and ConfigsPlease were getting something completely different. I've been assuming that the patcher was completely wiping out the majority of the files on each update, because that's what prior packs seemed to be doing, but it looks like it might only be changing files that have been specifically updated.

You may want to either include the directions to manually remove those folders for people with old installs OR change the pack folder name from BanishedTest to just Banished, which will give everyone a completely fresh install regardless.

**Comment by Mechalith** [comment]
On review: the FTB launcher appears to update any files still present in the pack, deletes and replaces the whole mod folder, and simply ignores any files that were present but are no longer in the pack. Since the dimension folders were in place already and your update didn't contain them anymore they were left unchanged.

**Comment by DrasticDemise** [comment]
In that case there isn't much I can do about it. This is a super minor bug and is really just a small annoyance at best.
