### ISSUE TITLE
Epic Siege +X-Ray + Obsidian blacklist and general balancing

### ISSUE THREAD

**Issue by Mechalith** [DrasticDemiseFTBPacks/Banished#77]
Just getting to the point where you can mine obsidian requires a bit in the way of setup, unless you get lucky and stumble on diamonds or Silent's gems and the dig spells don't work on it. Even then, completely surrounding a 9x9x3 in obsidian is going to take five stacks of obsidian. (320, to be precise, if you're leaving two blocks off as a door.) That's a lot of lava to come by, especially under constant assault by tunneling zombies and creepers, and periodic attacks from Lycanite's evil spawn. One could flood a large lava pool to get a floor or dig down to bedrock, which knocks approx 2 stacks off that requirement, but it's still going to be grueling.

I'm assuming that the attack crews will tunnel up or down as needed, as well as horizontally.

It might be desirable to add a Dark Power quest for obsidian, perhaps 10 power for 32 or 64 obsidian, so that there's a quick source of at least some of what a player is going to need. Alternately, possibly adding the bed to the griefing blacklist would be a good idea. That way even when swarms break through it'll be possible to recover instead of having to somehow tunnel/trek across 100+ blocks of dark space without most of your equipment. 

In the same vein, disabling creeper griefing might be a good idea. A single breakthrough (which will almost certainly happen within the first day or two of game time) can be a game ender if a creeper detonates next to your chests and/or bed.

The gist of all this is that I'm all for desperate and difficult situations. (I liked Blood n' Bones, afterall) What I'm less fond of is _hopeless_ situations, and this is closer to hopeless than I'd really like it to be. I know of plenty of ways to at least partially secure an area from Siege mobs, but they nearly all require resources and infrastructure that I'm not sure how to produce without any way to hide.

**Comment by Mechalith** [comment]
To be clear, I'm not just trying to be negative here. If there's a method for doing this that I'm not aware of, I'd love to know about it. As it stands I worry that very few players, if any, are going to play with the default configs. Given how much work has gone into and is going into the pack, I think it'd be a shame if discouragement drives off the majority of players.

**Comment by DrasticDemise** [comment]
Good ideas, I will see what I can do.

**Comment by DrasticDemise** [comment]
- Beds chests and obsidian will no longer be intentionally griefed 
- Can now get 32 obsidian for 10 DP
- Added a bunch of DP rewards to the main line
- No more Breaching Creepers

How does this sound?

**Comment by Mechalith** [comment]
Sounds solid to me.

**Comment by DrasticDemise** [comment]
Any other concerns?

**Comment by Mechalith** [comment]
Not regarding ESM specifically right now, but I do still think that the Dark Power system would work better as monster drops than as a rep meter if it can be made to function. HQM's implementation for rep grinding doesn't work very well when there's so many monsters in play.

**Comment by DrasticDemise** [comment]
The pack has well over a hundred or so mobs so it would be very difficult to attempt to balance out what mob gets how many drops if they get any at all. For instance, passive mobs couldn't have a drop since they would be breedable and if every mob has a drop you can set up an automatic mob farm that doesn't even require players to kill the mobs.  The other issue is that I didn't want to create a server currency out of it since it bypasses the entire progression system.

I would much rather use a different system but the HQM system is unfortunately my last resort that seems to work the best. I have also submitted an issue to their tracker so (maybe) it will get fixed.

**Comment by Mechalith** [comment]
I wonder how hard it'd be to write a micro-mod that just increments your rep upward by 1 (or however many) when you kill a hostile mob.

**Comment by DrasticDemise** [comment]
HQM is closed source so probably not easily.
