### ISSUE TITLE
EMC cheating with vortex infusion

### ISSUE THREAD

**Issue by QuImUfu** [DrasticDemiseFTBPacks/Banished#78]
With some vortex infusion recipes
(4 Blaze rods to 20 Blaze Powder, EMC*2,5, +9216 EMC;
 4 Iron to 32 Rails, EMC*~3, +2056 EMC;
 4 Blocks of Redstone to 1 Block of lapis, EMC*6,75, +6624 EMC;
 4 Sand to 1 Soul Sand, EMC*12,25, +45 EMC;
 4 Blocks of Iron to 1 Block of Gold, EMC*2, +9216 EMC) 
you can generate lot of EMC in a short time, because you can easily automate vortex infusion.
I think the Soul Sand recipe is ok, because you need something to power the vortex infusion witch will cost much more than 45EMC, but especially the blaze and the iron to Gold Block recipe are cheating.

**Comment by DrasticDemise** [comment]
Thanks, I will look into it.
