### ISSUE TITLE
Zombie Quest?

### ISSUE THREAD

**Issue by Milobe115** [DrasticDemiseFTBPacks/Banished#8]
The Zombie Essence Drain Quest is marked "Cooldown on completion" and not "Refreshing on interval". Though this might be intentional, it may also be an overlook.

Links to screenshots :
http://imgur.com/syLxIQb - Zombie ED Quest
http://imgur.com/1gkeZ03 - Blaze ED Quest

**Comment by DrasticDemise** [comment]
Do they function the same? It may be how HQM changes the text while it is on cool down as opposed to waiting to go on cool down.

**Comment by DrasticDemise** [comment]
Solved in next update.
