### ISSUE TITLE
srevers

### ISSUE THREAD

**Issue by kenk199** [DrasticDemiseFTBPacks/Banished#90]
the server download on FTB is broke 

 I think the eula is missing

**Comment by vdcc** [comment]
The server is not working for me too!

**Comment by DrasticDemise** [comment]
Delete the dynamic lighting mod and accept the eula

**Comment by vdcc** [comment]
It works now thanks so much! Looking forward to play it (:

**Comment by Slyrooster** [comment]
So, quick question, whenever I try to connect to my server it says Connection Lost then provides a list of rejected mods. Is there anyway I can fix this? Ill add the list of rejected mods below. Thanks!

http://puu.sh/kAQo8/6e4cd1847f.png

**Comment by vdcc** [comment]
This MIGHT work. Go to ftb-> edit mod pack-> open in folder and copy the problematic mods over to the server folder and replace those mods.

**Comment by DrasticDemise** [comment]
Your client is running on a newer version than the current files. You can move over those mods like vdcc said and it should work just fine.

**Comment by Slyrooster** [comment]
Thanks its up and running now <3
