### ISSUE TITLE
Died and my soulbound stuff didn't come back

### ISSUE THREAD

**Issue by Kezarious** [DrasticDemiseFTBPacks/Banished#92]
Using ver. 1.2.4

I was killed by one of those reaper-looking things, and my soulbound items, including my spellbound pick, spellbook, etc. and my player focus were lost. Seems like the gravestones also sometimes don't spawn on death, leaving me unable to recover my items since I haven't gotten any diamonds yet for the second focus quest. I've died a couple of times before in the pack, but the soulbound items did come back before.

Also, I'm curious, what's the clock for in the early game quests? Since it's a cave world, there doesn't seem to be any purpose for it.

**Comment by DrasticDemise** [comment]
The clock is because some mods require a certain time of day to perform specific actions. It is also useful because every 8th day is increased mob spawns and you can keep track of the days to prepare yourself.

**Comment by DrasticDemise** [comment]
Replacing gravestone with Guardian Chest - 

not to self - remember to do config
