### ISSUE TITLE
Weird player Spawn Glitch

### ISSUE THREAD

**Issue by VincentDraggy** [DrasticDemiseFTBPacks/Banished#93]
i was doing so well and then i get killed by a zombie pig and when i respawned, i didn't respawn at my bed, and i didn't respawn at the portal. For some reason i spawned randomly in a tiny little cave hundreds of blocks away from home with just one pickaxe and that ended up breaking before i could dig back to my home so i ended up getting stuck. I tried dying again, but i just respawned back where i spawned last time.

**Comment by Dragonic-magic** [comment]
i had this issue, three solutions, change the perfect spawn point in the files, use /gamemode 1 and get back then use your bed again, or three use the hqm book to get wood, then make a new pick and mine back and again reuse the bed

**Comment by ArcticHowler** [comment]
I was forced to use that second option myself... can't say that it's easy to mine your way back when it's either so dark you can't see, full of taint(that was a fun one...) or has so many enemies waiting in the darkness that you die over and over again before you can do anything...

**Comment by Dragonic-magic** [comment]
yeah pretty much i tried route 3 then 2, route one is only if you know how to modify the perfect spawn file in your save
