### ISSUE TITLE
Oddity in the Survival quests

### ISSUE THREAD

**Issue by ArcticHowler** [DrasticDemiseFTBPacks/Banished#96]
So I noticed that the survival quests which appear to be the basic "get started here" quests give ars magica spells that you can't use until you can make the ars magica book, which requires you delving deeply into the aura crusade stuff... I'm curious if there's a reason for this? I'm not saying it's a bad thing, but it just seems odd to get something you can't use for a fairly long time, especially when you have to set-up a base of operations so to speak quickly and said spells would greatly assist... Perhaps consider making it possibly to make the ars magica book an alternate way or something so that the spells don't take up inventory space instead of being useful? Loving this modpack thus far, but certain things are forcing me to use the gamemode cheat way too much(mostly the spawn issue and I did it for the book because I was tired of having spells I could never use in my inventory/chests, plus a few issues with mob spawns and the like in the form of me hating the reapers, hell not a fan of lycanites period but not why I made this post...)

**Comment by Dragonic-magic** [comment]
in SP you can immediately use Ars spells that you aquire, tho in multiplayer only the host seems to be able to that ive seen tho you could temp unlock the compendium then remove the book for other players, on a large scale like a public server not sure tho

**Comment by ArcticHowler** [comment]
I was unable to do such on SP, had to change gamemode and spawn the book in to use them(have to have the ui active in order to use the ars magica spells)

**Comment by ArcticHowler** [comment]
Hm... first world it wasn't allowing me to use the spells without the book,,, just made a new world to mess around(and I hate using creative even slightly) and it suddenly started working :s not sure what to say about that...
