### ISSUE TITLE
Crash while summoning phantoms

### ISSUE THREAD

**Issue by ArcticHowler** [DrasticDemiseFTBPacks/Banished#97]
So I had used that lycanites item that allows me to add mobs to the beastery(never used before tbh...) and discovered I could summon said mobs... was like "sweet revenge on the bastards!"... or so I thought, I was able to summon cinders just fine with no issues, but when I summoned phantoms the second time(did a test summon and then a real summon when I got a zombie stuck in the wall or something, he was spazzing out all over the place but didn't attack or do anything, using magnetism...) after a full charge(all of my summoning focus) the game crashed...

http://pastebin.com/hMVJHhR4

**Comment by DrasticDemise** [comment]
Might be fixed in the lastest versions of lycanites.
