### ISSUE TITLE
Obsidian Totem - Uncraftable? (Black Aura won't power Vortex Infuser)

### ISSUE THREAD

**Issue by 501warhead** [DrasticDemiseFTBPacks/Banished#99]
As the title suggests, basically after investigating Aura Cascade a bit and looking into the requirement for the crafting of Obsidian Totems I noticed something curious - it required Black Aura.

At first, as I had been playing through the mod I naturally just blindly followed the book on Aura Cascade so I was confused why it wasn't being powered, but as I began to understand further - Black Aura doesn't power machines. If Black Aura doesn't power machines, it's impossible to feed it into a Vortex Infuser to craft an Obsidian Totem.

I could, perhaps, be wrong on this one but at this time it does not seem like it's possible.

![image](https://cloud.githubusercontent.com/assets/11152237/10555508/4bf9d9ce-743e-11e5-9784-9d40c572d3ee.png)

![image](https://cloud.githubusercontent.com/assets/11152237/10555537/8a69712e-743e-11e5-8dc7-1e696d08aac1.png)

Images for reference.

**Comment by 501warhead** [comment]
I wasn't quite certain if this applied to anything else but I just noticed it also applies to Ender Air from Botania. I figure this was already considered, but I add it here for completeness.

**Comment by DrasticDemise** [comment]
Thank you, I will have these fixed next version.
